name: Terraform Deploy

on:
  push:
    branches:
      - dev
      - staging
      - prod
    paths-ignore:
      - '.github/workflows/**'
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging')) || (github.event_name == 'workflow_dispatch' && inputs.action == 'apply')

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::058264357476:role/iac-ci-cd-2
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.4

      - name: Set environment path
        id: env_path
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "env_path=environment/dev/" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "env_path=environment/staging/" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "prod" ]]; then
            echo "env_path=environment/prod/" >> $GITHUB_ENV
          else
            echo "Unknown branch"
            exit 1
          fi

      - name: Initialize Terraform
        run: |
          echo "Environment path is: ${{ env.env_path }}"
          cd ${{ env.env_path }}
          ls -la
          terraform init -backend-config="bucket=my-iac-states" -backend-config="key=${{ github.ref_name }}/terraform.tfstate"

      - name: Terraform Plan
        run: |
          cd ${{ env.env_path }}
          terraform plan 

      - name: Terraform Apply (for dev and staging)
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging'
        run: |
          cd ${{ env.env_path }}
          terraform apply -auto-approve 
      

  # Separate job for prod, requiring manual approval
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod  # This enables manual approval for the 'prod' environment
    if: github.ref == 'refs/heads/prod'

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::058264357476:role/iac-ci-cd-2
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.4

      - name: Initialize Terraform for Prod
        run: |
          cd environment/prod
          terraform init -backend-config="bucket=my-iac-states" -backend-config="key=prod/terraform.tfstate"
      - name: Terraform Plan
        run: |
          cd environment/prod
          terraform plan 

      - name: Terraform Apply for Prod
        if: inputs.action == 'apply'
        run: |
          cd environment/prod
          terraform apply -auto-approve 



  