name: Terraform Deploy

on:
  push:
    branches:
      - dev
      - staging
      - main
    paths-ignore:
      - '.github/workflows/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write      # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::058264357476:role/iac-ci-cd-2
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.4

      - name: Set environment path
        id: env_path
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "env_path=environment/dev/" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "stage" ]]; then
            echo "env_path=environment/stage/" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "env_path=environment/prod/" >> $GITHUB_ENV
          else
            echo "Unknown branch"
            exit 1
          fi
        
      - name: Initialize Terraform
        run: |
            echo "Environment path is: ${{ env.env_path }}"
            cd ${{ env.env_path }}
            ls -la 
            terraform init 

      - name: Terraform Plan
        run: |
          cd ${{ env.env_path }}
          terraform plan 

      - name: Terraform Apply
        if: github.ref == 'main' || github.ref == 'stage'
        run: |
            cd ${{ env.env_path }}
            terraform apply 
    

